import { DateTime } from "luxon";
import type { Story, TrafficSource, Appointment, Business, CategoryId, City, DB, MediaItem, Post, Professional, Service, User, WorkingRange } from "../domain/types";
import { getSlots, snapshotOf } from "../domain/booking";
import { TZ } from "../domain/time";

/**
 * Demo dataset. Every business, person, review and photo is fictional and marked
 * as demo/sample. Media are original illustrations generated by scripts/generate-sample-media.ts.
 */

export const DB_VERSION = 4;
const M = "media/";
const SOURCE = "איור מקורי שנוצר בקוד עבור הדמו (Beautigo)";

export const video = (name: string): MediaItem => ({ type: "video", src: `${M}${name}.mp4`, srcWebm: `${M}${name}.webm`, poster: `${M}${name}.jpg`, source: SOURCE });
export const image = (file: string): MediaItem => ({ type: "image", src: `${M}${file}.jpg`, source: SOURCE });

const CITIES: City[] = [
  { id: "tlv", name: "תל אביב-יפו", lat: 32.0853, lng: 34.7818, active: true },
  { id: "jlm", name: "ירושלים", lat: 31.7683, lng: 35.2137, active: true },
  { id: "hfa", name: "חיפה", lat: 32.794, lng: 34.9896, active: true },
  { id: "rg", name: "רמת גן", lat: 32.0684, lng: 34.8248, active: true },
  { id: "hrz", name: "הרצליה", lat: 32.1624, lng: 34.8447, active: true },
  { id: "rlz", name: "ראשון לציון", lat: 31.973, lng: 34.7925, active: true },
  { id: "ntn", name: "נתניה", lat: 32.3215, lng: 34.8532, active: true },
  { id: "bsh", name: "באר שבע", lat: 31.252, lng: 34.7915, active: true },
];

const week = (start: number, end: number, days = [0, 1, 2, 3, 4]): WorkingRange[] => days.map((weekday) => ({ weekday, start: start * 60, end: end * 60 }));
const friday = (start: number, end: number): WorkingRange[] => [{ weekday: 5, start: start * 60, end: end * 60 }];
const lunch = (h = 13, m = 0, days = [0, 1, 2, 3, 4]): WorkingRange[] => days.map((weekday) => ({ weekday, start: h * 60 + m, end: h * 60 + m + 30 }));

type SvcDef = Partial<Service> & { name: string; category: CategoryId; price: number; durationMin: number };
type ProDef = { name: string; title: string; specialties: string[]; services: number[]; hours?: WorkingRange[]; staffLogin?: string };
type PostDef = { kind: "reel" | "image" | "carousel"; media: string[]; caption: string; subtitle?: string; tags: string[]; svc?: number; pro?: number; daysAgo: number; likes?: number; saves?: number; views?: number; city?: string };
type BizDef = {
  id: string;
  name: string;
  username: string;
  description: string;
  categories: CategoryId[];
  cityId: string;
  address: string;
  serviceAreas?: string[];
  mobile?: boolean;
  cover: string;
  avatar: string;
  owner: { id: string; name: string };
  services: SvcDef[];
  pros: ProDef[];
  posts: PostDef[];
  status?: Business["status"];
};

const BIZ: BizDef[] = [
  {
    id: "b-nova",
    name: "סטודיו נובה",
    username: "nova.studio",
    description: "סטודיו לשיער בלב תל אביב. בלייאז׳ טבעי, תספורות שקל לסדר בבית וצבע שמחזיק.",
    categories: ["hair", "stylist", "blowdry"],
    cityId: "tlv",
    address: "רחוב הדוגמה 12, תל אביב-יפו",
    cover: "cover-hair",
    avatar: "square-hair",
    owner: { id: "u-owner-nova", name: "מאיה רוזן" },
    services: [
      { name: "תספורת נשים", category: "hair", price: 220, durationMin: 60, bufferMin: 10 },
      { name: "פן ועיצוב", category: "blowdry", price: 140, durationMin: 45, bufferMin: 5 },
      { name: "צבע שורשים", category: "hair", price: 320, durationMin: 90, bufferMin: 15, payment: "deposit", deposit: { type: "fixed", value: 100 } },
      { name: "בלייאז׳", category: "stylist", price: 950, priceFrom: true, durationMin: 180, bufferMin: 15, approval: "manual", payment: "deposit", deposit: { type: "percent", value: 30 }, description: "המחיר הסופי לפי אורך ועובי השיער. העסק מאשר כל בקשה." },
    ],
    pros: [
      { name: "מאיה רוזן", title: "מעצבת שיער ובעלים", specialties: ["בלייאז׳", "תספורות"], services: [0, 1, 3] },
      { name: "דניאל כהן", title: "קולוריסט", specialties: ["צבע", "גוונים"], services: [2, 3], hours: [...week(10, 19), ...friday(9, 14)] },
      { name: "נועה לוי", title: "מעצבת שיער", specialties: ["פן", "תסרוקות"], services: [0, 1], staffLogin: "u-staff-noa" },
    ],
    posts: [
      { kind: "reel", media: ["hair-honey"], caption: "בלייאז׳ דבש רך עם מעבר בלי קו", subtitle: "שלוש שעות, צבע אחד, אפס קווים", tags: ["בלייאז׳", "דבש", "גוונים"], svc: 3, pro: 0, daysAgo: 0.4, likes: 412, saves: 96, views: 5200 },
      { kind: "reel", media: ["hair-ash"], caption: "שכבות אוורריות על בלונד אפרפר", tags: ["שכבות", "בלונד"], svc: 0, pro: 2, daysAgo: 2, likes: 188, saves: 40, views: 2100 },
      { kind: "reel", media: ["braid-honey"], caption: "צמה הולנדית לאירוע ערב", tags: ["צמות", "אירוע"], svc: 1, pro: 2, daysAgo: 5, likes: 96, saves: 31, views: 1400 },
      { kind: "carousel", media: ["hair-honey", "hair-ash", "braid-honey"], caption: "שלושה לוקים מהשבוע בסטודיו", tags: ["השראה", "שיער"], daysAgo: 3, likes: 140, saves: 52, views: 1900 },
    ],
  },
  {
    id: "b-blade",
    name: "בלייד לאב",
    username: "bladelab.tlv",
    description: "ברברשופ שכונתי. פייד חד, זקן מסודר, מגיעים בזמן ויוצאים מסודרים.",
    categories: ["barber"],
    cityId: "tlv",
    address: "שדרות הדוגמה 40, תל אביב-יפו",
    cover: "cover-barber",
    avatar: "square-barber",
    owner: { id: "u-owner-blade", name: "אבי מזרחי" },
    services: [
      { name: "תספורת גברים", category: "barber", price: 90, durationMin: 30, bufferMin: 5 },
      { name: "פייד + זקן", category: "barber", price: 130, durationMin: 45, bufferMin: 5 },
      { name: "עיצוב זקן", category: "barber", price: 60, durationMin: 20, bufferMin: 5 },
    ],
    pros: [
      { name: "אבי מזרחי", title: "ברבר ובעלים", specialties: ["סקין פייד"], services: [0, 1, 2], hours: [...week(9, 20), ...friday(8, 15)] },
      { name: "טל ביטון", title: "ברבר", specialties: ["זקן", "קלאסי"], services: [0, 2], hours: [...week(11, 20), ...friday(8, 15)] },
    ],
    posts: [
      { kind: "reel", media: ["fade-dark"], caption: "סקין פייד עם ליין־אפ חד", subtitle: "45 דקות, מכונה ומספריים", tags: ["פייד", "ליין־אפ"], svc: 1, pro: 0, daysAgo: 0.8, likes: 302, saves: 44, views: 4100 },
      { kind: "image", media: ["cover-barber"], caption: "הכיסא פנוי מחר מ־11:00", tags: ["ברבר"], daysAgo: 1.5, likes: 60, saves: 4, views: 800 },
    ],
  },
  {
    id: "b-atelier",
    name: "אטלייה לק",
    username: "atelier.lak",
    description: "סטודיו בוטיק לציפורניים. ג׳ל עמיד, פרנץ׳ דק ועיצובים בהתאמה אישית.",
    categories: ["nails"],
    cityId: "rg",
    address: "רחוב הדוגמה 7, רמת גן",
    cover: "cover-nails",
    avatar: "square-nails",
    owner: { id: "u-owner-atelier", name: "שירן דוד" },
    services: [
      { name: "מניקור ג׳ל", category: "nails", price: 150, durationMin: 60, bufferMin: 10 },
      { name: "מניקור צרפתי", category: "nails", price: 180, durationMin: 75, bufferMin: 10 },
      { name: "בניית ציפורניים", category: "nails", price: 280, durationMin: 105, bufferMin: 15, payment: "deposit", deposit: { type: "fixed", value: 50 } },
    ],
    pros: [
      { name: "שירן דוד", title: "מניקוריסטית ובעלים", specialties: ["ג׳ל", "בנייה"], services: [0, 1, 2] },
      { name: "ליה אוחיון", title: "נייל ארטיסטית", specialties: ["פרנץ׳", "עיצובים"], services: [0, 1], hours: [...week(12, 20), ...friday(8, 13)] },
    ],
    posts: [
      { kind: "reel", media: ["nails-nude"], caption: "נוד חלבי לשגרה — מניקור ג׳ל", tags: ["נוד", "ג׳ל", "מינימליסטי"], svc: 0, pro: 0, daysAgo: 0.3, likes: 520, saves: 130, views: 6100 },
      { kind: "reel", media: ["nails-french"], caption: "פרנץ׳ דק ונקי", tags: ["פרנץ׳", "קלאסי"], svc: 1, pro: 1, daysAgo: 4, likes: 210, saves: 70, views: 2600 },
      { kind: "image", media: ["square-nails"], caption: "תוצאה אחרי שלושה שבועות", tags: ["ג׳ל", "עמידות"], svc: 0, daysAgo: 6, likes: 90, saves: 21, views: 900 },
    ],
  },
  {
    id: "b-chrome",
    name: "כרום נייל בר",
    username: "chrome.nailbar",
    description: "כרום, אלמנד ובורגונדי עמוק. נייל בר בהרצליה עם שירות לתל אביב.",
    categories: ["nails"],
    cityId: "hrz",
    serviceAreas: ["tlv"],
    address: "רחוב הדוגמה 3, הרצליה",
    cover: "cover-gel",
    avatar: "square-gel",
    owner: { id: "u-owner-chrome", name: "רוני שגיא" },
    services: [
      { name: "ג׳ל כרום", category: "nails", price: 190, durationMin: 75, bufferMin: 10 },
      { name: "עיצוב בהתאמה אישית", category: "nails", price: 220, priceFrom: true, durationMin: 120, bufferMin: 15, approval: "manual", description: "שלחו השראה — העסק מאשר ומתאים מחיר סופי." },
    ],
    pros: [
      { name: "רוני שגיא", title: "נייל ארטיסטית", specialties: ["כרום", "אלמנד"], services: [0, 1] },
      { name: "עדן פרץ", title: "מניקוריסטית", specialties: ["בורגונדי", "ג׳ל"], services: [0] },
    ],
    posts: [
      { kind: "reel", media: ["nails-chrome"], caption: "כרום פנינה על אלמנד", tags: ["כרום", "אלמנד"], svc: 1, pro: 0, daysAgo: 1.2, likes: 330, saves: 88, views: 3900 },
      { kind: "reel", media: ["nails-burgundy"], caption: "בורגונדי עמוק לסתיו", tags: ["בורגונדי", "סתיו", "ג׳ל"], svc: 0, pro: 1, daysAgo: 2.5, likes: 280, saves: 61, views: 3300, city: "tlv" },
    ],
  },
  {
    id: "b-gloss",
    name: "גלוס בר",
    username: "gloss.bar",
    description: "בר פן ועיצוב: פן חלק, גלים רכים ותסרוקות ערב.",
    categories: ["blowdry", "stylist"],
    cityId: "hrz",
    address: "רחוב הדוגמה 21, הרצליה",
    cover: "cover-blowout",
    avatar: "square-blowout",
    owner: { id: "u-owner-gloss", name: "ליאת כץ" },
    services: [
      { name: "פן חלק", category: "blowdry", price: 110, durationMin: 40, bufferMin: 5 },
      { name: "פן גלי", category: "blowdry", price: 140, durationMin: 50, bufferMin: 5 },
      { name: "תסרוקת ערב", category: "stylist", price: 260, durationMin: 60, bufferMin: 10, payment: "deposit", deposit: { type: "percent", value: 25 } },
    ],
    pros: [
      { name: "ליאת כץ", title: "מעצבת שיער", specialties: ["תסרוקות ערב"], services: [0, 1, 2] },
      { name: "עדי שמש", title: "מעצבת פן", specialties: ["פן גלי"], services: [0, 1] },
    ],
    posts: [
      { kind: "reel", media: ["blowout-honey"], caption: "גלים רכים עם נפח מהשורש", tags: ["גלים", "נפח", "פן"], svc: 1, pro: 1, daysAgo: 1, likes: 240, saves: 50, views: 2800 },
      { kind: "reel", media: ["blowout-espresso"], caption: "פן חלק ומבריק על שיער כהה", tags: ["פן", "ברק"], svc: 0, pro: 0, daysAgo: 3.5, likes: 150, saves: 33, views: 1700 },
    ],
  },
  {
    id: "b-libi",
    name: "ליבי מייקאפ",
    username: "libi.makeup",
    description: "מאפרת ניידת לאירועים וכלות. מגיעה אליכן בתל אביב, רמת גן, הרצליה וראשון לציון.",
    categories: ["makeup"],
    cityId: "tlv",
    serviceAreas: ["rg", "hrz", "rlz"],
    mobile: true,
    address: "שירות נייד — מגיעה אליך",
    cover: "cover-makeup",
    avatar: "square-makeup",
    owner: { id: "u-owner-libi", name: "ליבי אדרי" },
    services: [
      { name: "איפור ערב", category: "makeup", price: 380, durationMin: 60, bufferMin: 30 },
      { name: "איפור כלה", category: "makeup", price: 1600, priceFrom: true, durationMin: 120, bufferMin: 45, approval: "manual", payment: "deposit", deposit: { type: "fixed", value: 300 }, description: "כולל ניסיון. ההזמנה מאושרת ידנית לפי מיקום ושעה." },
    ],
    pros: [
      { name: "ליבי אדרי", title: "מאפרת", specialties: ["כלות", "איפור טבעי"], services: [0, 1], hours: [...week(8, 20, [0, 1, 2, 3, 4, 5])] },
      { name: "סתיו נחום", title: "מאפרת", specialties: ["ערב", "שפתיים"], services: [0], hours: [...week(10, 20)] },
    ],
    posts: [
      { kind: "reel", media: ["makeup-rose"], caption: "פלטת ורוד־עתיק לערב", tags: ["ערב", "ורוד"], svc: 0, pro: 0, daysAgo: 0.6, likes: 270, saves: 77, views: 3500 },
      { kind: "reel", media: ["lips-red"], caption: "אדום קלאסי שמחזיק כל הערב", tags: ["שפתיים", "אדום"], svc: 0, pro: 1, daysAgo: 2.2, likes: 199, saves: 45, views: 2500, city: "rg" },
    ],
  },
  {
    id: "b-kav",
    name: "סטודיו קו",
    username: "studio.kav",
    description: "איפור וגבות בירושלים. מראה נקי בגוונים חמים.",
    categories: ["makeup", "brows"],
    cityId: "jlm",
    address: "רחוב הדוגמה 5, ירושלים",
    cover: "cover-lips",
    avatar: "square-lips",
    owner: { id: "u-owner-kav", name: "מירה לוי" },
    services: [
      { name: "איפור יום", category: "makeup", price: 250, durationMin: 45, bufferMin: 15 },
      { name: "שיעור איפור אישי", category: "makeup", price: 420, durationMin: 90, bufferMin: 15 },
      { name: "עיצוב גבות", category: "brows", price: 90, durationMin: 30, bufferMin: 5 },
    ],
    pros: [
      { name: "מירה לוי", title: "מאפרת", specialties: ["ברונזה", "שיעורים"], services: [0, 1, 2] },
      { name: "הדס בן חיים", title: "מעצבת גבות", specialties: ["גבות"], services: [2] },
    ],
    posts: [
      { kind: "reel", media: ["makeup-bronze"], caption: "ברונזה חמה ליום", tags: ["ברונזה", "טבעי"], svc: 0, pro: 0, daysAgo: 1.8, likes: 120, saves: 30, views: 1500 },
      { kind: "reel", media: ["lips-nude"], caption: "נוד לשפתיים — שיעור קצר", tags: ["שפתיים", "נוד"], svc: 1, pro: 0, daysAgo: 6, likes: 88, saves: 19, views: 1100 },
    ],
  },
  {
    id: "b-brow",
    name: "בראו ביוטי",
    username: "brow.beauty",
    description: "הרמת ריסים וגבות טבעיות בחיפה.",
    categories: ["brows"],
    cityId: "hfa",
    address: "שדרות הדוגמה 18, חיפה",
    cover: "cover-brows",
    avatar: "square-brows",
    owner: { id: "u-owner-brow", name: "רונית שמש" },
    services: [
      { name: "הרמת ריסים", category: "brows", price: 220, durationMin: 60, bufferMin: 10 },
      { name: "למינציה לגבות", category: "brows", price: 200, durationMin: 45, bufferMin: 10 },
    ],
    pros: [
      { name: "רונית שמש", title: "מומחית גבות וריסים", specialties: ["למינציה"], services: [0, 1] },
      { name: "יעל חורי", title: "מעצבת גבות", specialties: ["הרמת ריסים"], services: [0] },
    ],
    posts: [
      { kind: "reel", media: ["lashes-soft"], caption: "הרמת ריסים — מראה פתוח בלי מסקרה", tags: ["ריסים", "טבעי"], svc: 0, pro: 1, daysAgo: 2, likes: 160, saves: 41, views: 2000 },
      { kind: "reel", media: ["lashes-deep"], caption: "למינציה לגבות מלאות", tags: ["גבות", "למינציה"], svc: 1, pro: 0, daysAgo: 7, likes: 101, saves: 22, views: 1300 },
    ],
  },
  {
    id: "b-skin",
    name: "עור נקי",
    username: "clean.skin",
    description: "קליניקת טיפוח עור. טיפולי פנים מותאמים וסרומים.",
    categories: ["skincare"],
    cityId: "tlv",
    address: "רחוב הדוגמה 30, תל אביב-יפו",
    cover: "cover-skincare",
    avatar: "square-skincare",
    owner: { id: "u-owner-skin", name: "אורית גל" },
    services: [
      { name: "טיפול פנים קלאסי", category: "skincare", price: 340, durationMin: 60, bufferMin: 15 },
      { name: "טיפול לחות עמוק", category: "skincare", price: 420, durationMin: 75, bufferMin: 15, payment: "deposit", deposit: { type: "percent", value: 20 } },
    ],
    pros: [
      { name: "אורית גל", title: "קוסמטיקאית", specialties: ["לחות", "אקנה"], services: [0, 1] },
      { name: "שני דהן", title: "קוסמטיקאית", specialties: ["טיפול קלאסי"], services: [0] },
    ],
    posts: [
      { kind: "reel", media: ["skincare-light"], caption: "סרום בוקר בשלוש טיפות", tags: ["סרום", "לחות"], svc: 1, pro: 0, daysAgo: 1.4, likes: 140, saves: 66, views: 1800 },
      { kind: "reel", media: ["skincare-dark"], caption: "שגרת ערב לעור רגיש", tags: ["שגרת ערב", "עור רגיש"], svc: 0, pro: 1, daysAgo: 4.5, likes: 92, saves: 38, views: 1200 },
    ],
  },
  {
    id: "b-carmel",
    name: "הספר של הכרמל",
    username: "carmel.barber",
    description: "ספר משפחתי בחיפה. תספורות ילדים, פייד וגילוח במגבת חמה.",
    categories: ["barber"],
    cityId: "hfa",
    address: "רחוב הדוגמה 9, חיפה",
    cover: "cover-braid",
    avatar: "square-braid",
    owner: { id: "u-owner-carmel", name: "יוסי חדד" },
    services: [
      { name: "תספורת גברים", category: "barber", price: 80, durationMin: 30, bufferMin: 5 },
      { name: "תספורת ילדים", category: "barber", price: 60, durationMin: 25, bufferMin: 5 },
    ],
    pros: [
      { name: "יוסי חדד", title: "ספר", specialties: ["קלאסי", "ילדים"], services: [0, 1] },
      { name: "עומר חדד", title: "ספר", specialties: ["פייד"], services: [0] },
    ],
    posts: [{ kind: "reel", media: ["fade-light"], caption: "מעבר רך לשגרה", tags: ["פייד", "קלאסי"], svc: 0, pro: 1, daysAgo: 3, likes: 70, saves: 9, views: 900 }],
  },
  {
    id: "b-color",
    name: "צבע ופן ירושלים",
    username: "color.jlm",
    description: "צבע, נחושת וצמות. סלון שיער ותיק במרכז העיר.",
    categories: ["hair", "stylist"],
    cityId: "jlm",
    address: "רחוב הדוגמה 14, ירושלים",
    cover: "cover-color",
    avatar: "square-color",
    owner: { id: "u-owner-color", name: "שרה אלון" },
    services: [
      { name: "צבע מלא", category: "hair", price: 380, durationMin: 120, bufferMin: 15 },
      { name: "צמות", category: "stylist", price: 120, durationMin: 45, bufferMin: 5 },
    ],
    pros: [
      { name: "שרה אלון", title: "קולוריסטית", specialties: ["נחושת"], services: [0, 1] },
      { name: "תמר אביטל", title: "מעצבת שיער", specialties: ["צמות"], services: [1] },
    ],
    posts: [
      { kind: "reel", media: ["hair-copper"], caption: "נחושת חמה לחורף", tags: ["נחושת", "צבע"], svc: 0, pro: 0, daysAgo: 2.8, likes: 130, saves: 28, views: 1600 },
      { kind: "reel", media: ["braid-ash"], caption: "צמה רכה לערב", tags: ["צמות", "ערב"], svc: 1, pro: 1, daysAgo: 8, likes: 64, saves: 12, views: 700 },
    ],
  },
  {
    id: "b-rishon",
    name: "ביוטי בר ראשון",
    username: "beautybar.rishon",
    description: "ציפורניים וגבות בראשון לציון. עוד אין לנו רילס — רק תמונות מהסטודיו.",
    categories: ["nails", "brows"],
    cityId: "rlz",
    address: "רחוב הדוגמה 2, ראשון לציון",
    cover: "cover-nails",
    avatar: "square-lashes",
    owner: { id: "u-owner-rishon", name: "קרן ממן" },
    services: [
      { name: "לק ג׳ל", category: "nails", price: 130, durationMin: 50, bufferMin: 10 },
      { name: "עיצוב גבות", category: "brows", price: 70, durationMin: 25, bufferMin: 5 },
    ],
    pros: [
      { name: "קרן ממן", title: "מניקוריסטית", specialties: ["ג׳ל"], services: [0, 1] },
      { name: "מורן אזולאי", title: "מעצבת גבות", specialties: ["גבות"], services: [1] },
    ],
    posts: [
      { kind: "image", media: ["nails-burgundy"], caption: "בורגונדי לסוף השבוע", tags: ["בורגונדי", "ג׳ל"], svc: 0, pro: 0, daysAgo: 1, likes: 40, saves: 6, views: 400 },
      { kind: "carousel", media: ["nails-french", "square-nails"], caption: "לפני ואחרי", tags: ["פרנץ׳"], svc: 0, pro: 0, daysAgo: 5, likes: 35, saves: 8, views: 380 },
    ],
  },
  {
    id: "b-pending",
    name: "סטודיו חדש בנתניה",
    username: "new.netanya",
    description: "עסק לדוגמה שממתין לבדיקת הפלטפורמה.",
    categories: ["hair"],
    cityId: "ntn",
    address: "רחוב הדוגמה 1, נתניה",
    cover: "cover-color",
    avatar: "square-color",
    owner: { id: "u-owner-pending", name: "גיל אורן" },
    services: [{ name: "תספורת", category: "hair", price: 150, durationMin: 45, bufferMin: 5 }],
    pros: [{ name: "גיל אורן", title: "מעצב שיער", specialties: [], services: [0] }],
    posts: [],
    status: "pending",
  },
];

const PRIVACY = { privateSaves: false, showFollowing: true, allowMessagesFromBusinesses: true };

function user(id: string, name: string, username: string, role: User["role"], extra: Partial<User> = {}): User {
  return {
    id,
    name,
    username,
    role,
    interests: [],
    followingBusinesses: [],
    followingPros: [],
    blockedUserIds: [],
    blockedBusinessIds: [],
    status: "active",
    isDemo: true,
    createdAt: "2026-01-01T09:00:00.000Z",
    privacy: { ...PRIVACY },
    ...extra,
  };
}

export const DEMO_ACCOUNTS = {
  customer: "u-dana",
  owner: "u-owner-nova",
  staff: "u-staff-noa",
  admin: "u-admin",
};

export function createSeed(nowDate = new Date()): DB {
  const now = DateTime.fromJSDate(nowDate).setZone(TZ);
  const iso = (d: DateTime) => d.toUTC().toISO()!;
  const db: DB = {
    version: DB_VERSION,
    cities: CITIES.map((c) => ({ ...c })),
    users: [
      user("u-dana", "דנה כהן", "dana.cohen", "customer", { cityId: "tlv", interests: ["hair", "nails", "blowdry"], email: "dana@demo.beautigo", phone: "050-0000001" }),
      user("u-yoav", "יואב לוי", "yoav.levi", "customer", { cityId: "rg", interests: ["barber"] }),
      user("u-michal", "מיכל אברהם", "michal.a", "customer", { cityId: "jlm", interests: ["makeup", "brows"] }),
      user("u-neta", "נטע ברק", "neta.b", "customer", { cityId: "tlv", interests: ["nails"] }),
      user("u-ron", "רון אשכנזי", "ron.a", "customer", { cityId: "hfa", interests: ["barber"] }),
      user("u-shira", "שירה פרידמן", "shira.f", "customer", { cityId: "hrz", interests: ["blowdry", "makeup"] }),
      user("u-admin", "צוות Beautigo", "beautigo.team", "admin"),
    ],
    businesses: [],
    professionals: [],
    services: [],
    posts: [],
    stories: [],
    comments: [],
    collections: [],
    appointments: [],
    blockedTimes: [],
    reviews: [],
    conversations: [],
    notifications: [],
    reports: [],
    campaigns: [],
    payments: [],
    audit: [],
    integrationEvents: [],
    analytics: [],
  };

  for (const d of BIZ) {
    db.users.push(user(d.owner.id, d.owner.name, d.username + ".owner", "business", { businessId: d.id, cityId: d.cityId }));
    const biz: Business = {
      id: d.id,
      name: d.name,
      username: d.username,
      description: d.description,
      categories: d.categories,
      cityId: d.cityId,
      address: d.address,
      serviceAreaCityIds: d.serviceAreas ?? [],
      isMobile: !!d.mobile,
      cover: `${M}${d.cover}.jpg`,
      avatar: `${M}${d.avatar}.jpg`,
      ownerId: d.owner.id,
      status: d.status ?? "active",
      isDemo: true,
      phone: "03-0000000",
      openingHours: [...week(9, 19), ...friday(8, 14)],
      policy: {
        cancelHours: 24,
        requestExpiryHours: 24,
        paymentHoldMinutes: 15,
        text: "ביטול או שינוי ללא עלות עד 24 שעות לפני התור. ביטול מאוחר — מקדמה (אם שולמה) לא מוחזרת.",
      },
      pinnedPostIds: [],
      quickReplies: ["תודה! נתראה בתור 😊", "אפשר לשלוח תמונת השראה?", "יש לנו מקום פנוי מחר בבוקר", "המחיר הסופי ייקבע בייעוץ קצר בסטודיו"],
      calendar: { status: "disconnected" },
      createdAt: "2026-02-01T09:00:00.000Z",
    };
    db.businesses.push(biz);

    const services: Service[] = d.services.map((s, i) => ({
      id: `${d.id}-s${i}`,
      businessId: d.id,
      description: "",
      bufferMin: 0,
      priceFrom: false,
      approval: "auto",
      payment: "at_business",
      deposit: { type: "fixed", value: 0 },
      active: true,
      ...s,
    }));
    db.services.push(...services);

    d.pros.forEach((p, i) => {
      const pro: Professional = {
        id: `${d.id}-p${i}`,
        businessId: d.id,
        name: p.name,
        title: p.title,
        specialties: p.specialties,
        avatar: "",
        serviceIds: p.services.map((x) => services[x].id),
        workingHours: p.hours ?? [...week(9, 19), ...friday(8, 14)],
        breaks: lunch(13, i % 2 ? 30 : 0),
        active: true,
      };
      db.professionals.push(pro);
      if (p.staffLogin) db.users.push(user(p.staffLogin, p.name, d.username + "." + i, "staff", { businessId: d.id, professionalId: pro.id }));
    });

    d.posts.forEach((p, i) => {
      const media = p.kind === "reel" ? [video(p.media[0])] : p.media.map(image);
      const published = now.minus({ hours: p.daysAgo * 24 });
      const post: Post = {
        id: `${d.id}-post${i}`,
        businessId: d.id,
        kind: p.kind,
        media,
        cover: media[0].poster ?? media[0].src,
        caption: p.caption,
        subtitle: p.subtitle,
        tags: p.tags,
        cityId: p.city ?? d.cityId,
        serviceId: p.svc != null ? services[p.svc].id : undefined,
        professionalId: p.pro != null ? `${d.id}-p${p.pro}` : undefined,
        status: "published",
        likedBy: [],
        savedCount: p.saves ?? 0,
        views: p.views ?? 0,
        shares: Math.round((p.likes ?? 0) / 12),
        createdAt: iso(published),
        publishedAt: iso(published),
        isSample: true,
      };
      // demo like counts: represented by placeholder ids so totals are visible
      post.likedBy = Array.from({ length: p.likes ?? 0 }, (_, k) => `demo-liker-${k}`);
      db.posts.push(post);
    });
  }

  const B = (id: string) => db.businesses.find((b) => b.id === id)!;
  B("b-nova").pinnedPostIds = ["b-nova-post0"];
  B("b-nova").calendar = { status: "connected", accountEmail: "nova.studio@demo.example", calendarId: "nova-main", calendarName: "יומן סטודיו נובה", lastSyncAt: iso(now.minus({ minutes: 12 })) };
  B("b-gloss").calendar = { status: "error", accountEmail: "gloss@demo.example", calendarId: "gloss", calendarName: "תורים — גלוס בר", lastSyncAt: iso(now.minus({ days: 2 })), lastError: "ההרשאה פגה (invalid_grant). יש להתחבר מחדש." };
  db.integrationEvents.push({ id: "ie1", businessId: "b-gloss", integration: "google_calendar", level: "error", message: "סנכרון נכשל: invalid_grant — נדרש חיבור מחדש (דמו)", createdAt: iso(now.minus({ days: 2 })), resolved: false });

  // Social graph
  const dana = db.users.find((u) => u.id === "u-dana")!;
  dana.followingBusinesses = ["b-nova", "b-atelier", "b-gloss"];
  dana.followingPros = ["b-chrome-p0"];
  db.users.find((u) => u.id === "u-yoav")!.followingBusinesses = ["b-blade"];
  const like = (postId: string, uid: string) => db.posts.find((p) => p.id === postId)!.likedBy.push(uid);
  like("b-nova-post0", "u-dana");
  like("b-atelier-post0", "u-dana");
  db.collections.push(
    { id: "col-1", userId: "u-dana", name: "השראה לחתונה", postIds: ["b-nova-post0", "b-libi-post0", "b-gloss-post0"], createdAt: iso(now.minus({ days: 6 })) },
    { id: "col-2", userId: "u-dana", name: "ציפורניים לקיץ", postIds: ["b-atelier-post0", "b-chrome-post0"], createdAt: iso(now.minus({ days: 3 })) },
  );
  db.comments.push(
    { id: "c1", postId: "b-nova-post0", userId: "u-neta", text: "המעבר מושלם! כמה זמן זה מחזיק?", createdAt: iso(now.minus({ hours: 5 })), hidden: false },
    { id: "c2", postId: "b-nova-post0", userId: "u-owner-nova", text: "תודה נטע! בערך 3–4 חודשים עם טיפוח נכון", createdAt: iso(now.minus({ hours: 4 })), hidden: false },
    { id: "c3", postId: "b-atelier-post0", userId: "u-shira", text: "איזה גוון זה בדיוק?", createdAt: iso(now.minus({ hours: 2 })), hidden: false },
    { id: "c4", postId: "b-blade-post0", userId: "u-ron", text: "קישור לאתר זול יותר >>> spam.example", createdAt: iso(now.minus({ hours: 9 })), hidden: false },
    { id: "c5", postId: "b-nova-post0", userId: "u-dana", text: "@nova.studio אפשר כזה גם על שיער קצר? #בלייאז׳", createdAt: iso(now.minus({ hours: 3 })), hidden: false, likedBy: ["u-neta", "u-shira"] },
    { id: "c6", postId: "b-nova-post0", userId: "u-owner-nova", text: "@dana.cohen בטח! על קצר זה יוצא עוד יותר רך", createdAt: iso(now.minus({ hours: 2 })), hidden: false, parentId: "c5", likedBy: ["u-dana"] },
    { id: "c7", postId: "b-atelier-post0", userId: "u-owner-atelier", text: "@shira.f זה נוד חלבי 103 של הסטודיו 💅", createdAt: iso(now.minus({ hours: 1 })), hidden: false, parentId: "c3" },
    { id: "c8", postId: "b-chrome-post0", userId: "u-neta", text: "הכרום הזה 😍 שומרת לחתונה", createdAt: iso(now.minus({ hours: 7 })), hidden: false, likedBy: ["u-dana", "u-michal", "u-shira"] },
  );
  db.comments.find((c) => c.id === "c2")!.likedBy = ["u-neta", "u-dana"];
  db.comments.find((c) => c.id === "c1")!.likedBy = ["u-dana"];

  // Appointments placed into real free slots so the demo calendar is valid
  const book = (o: {
    biz: string;
    svc: number;
    pro?: number;
    dayOffset: number;
    pick: number;
    customerId?: string;
    guestName?: string;
    status: Appointment["status"];
    source?: string;
    inspo?: string[];
    note?: string;
  }) => {
    const business = B(o.biz);
    const service = db.services.find((s) => s.id === `${o.biz}-s${o.svc}`)!;
    const proId = o.pro != null ? `${o.biz}-p${o.pro}` : null;
    // Past appointments: search slots as if "now" were a week earlier
    const ref = o.dayOffset < 0 ? now.plus({ days: o.dayOffset - 1 }).toJSDate() : nowDate;
    for (let k = 0; k < 7; k++) {
      const date = now.plus({ days: o.dayOffset + k }).toISODate()!;
      const slots = getSlots(db, { businessId: business.id, serviceId: service.id, date, professionalId: proId }, ref);
      const slot = slots[Math.min(o.pick, slots.length - 1)];
      if (!slot) continue;
      const start = new Date(slot.start);
      const a: Appointment = {
        id: `apt-${db.appointments.length + 1}`,
        businessId: business.id,
        customerId: o.customerId,
        guestName: o.guestName,
        professionalId: proId ?? slot.professionalIds[0],
        serviceId: service.id,
        snapshot: snapshotOf(service, business),
        start: start.toISOString(),
        end: new Date(start.getTime() + service.durationMin * 60_000).toISOString(),
        status: o.status,
        holdExpiresAt:
          o.status === "pending_approval" ? iso(now.plus({ hours: 20 })) : o.status === "pending_payment" ? iso(now.plus({ minutes: 14 })) : undefined,
        sourcePostId: o.source,
        inspirationPostIds: o.inspo ?? [],
        note: o.note,
        payment: { status: "none", amount: 0 },
        history: [{ at: iso(now.minus({ days: 2 })), by: o.customerId ?? business.ownerId, action: o.customerId ? "created" : "created_manual" }],
        createdAt: iso(o.dayOffset < 0 ? now.plus({ days: o.dayOffset - 3 }) : now.minus({ days: 2 })),
        createdBy: o.customerId ? "customer" : "business",
      };
      if (o.status === "confirmed" && service.payment === "deposit") a.payment = { status: "paid_demo", amount: a.snapshot.deposit };
      db.appointments.push(a);
      return a;
    }
    throw new Error("seed: no slot for " + o.biz);
  };

  // Dana: upcoming confirmed from a reel, pending approval, pending payment, completed (reviewable), completed+reviewed, cancelled
  const a1 = book({ biz: "b-nova", svc: 0, pro: 0, dayOffset: 2, pick: 3, customerId: "u-dana", status: "confirmed", source: "b-nova-post1", inspo: ["b-nova-post1"], note: "רוצה לשמור על האורך" });
  const a2 = book({ biz: "b-libi", svc: 1, dayOffset: 9, pick: 1, customerId: "u-dana", status: "pending_approval", source: "b-libi-post0", inspo: ["b-libi-post0", "b-nova-post0"], note: "חתונה בגן אירועים, צריך להגיע עד 16:00" });
  book({ biz: "b-atelier", svc: 2, pro: 0, dayOffset: 4, pick: 2, customerId: "u-dana", status: "pending_payment", source: "b-atelier-post0", inspo: ["b-atelier-post0"] });
  const past1 = book({ biz: "b-blade", svc: 0, pro: 1, dayOffset: -6, pick: 2, customerId: "u-dana", status: "completed" });
  const past2 = book({ biz: "b-gloss", svc: 1, pro: 1, dayOffset: -12, pick: 1, customerId: "u-dana", status: "completed", source: "b-gloss-post0" });
  book({ biz: "b-skin", svc: 0, dayOffset: -3, pick: 4, customerId: "u-dana", status: "cancelled" }).cancelReason = "ביטלתי בגלל מילואים של בן הזוג";
  void past1;

  // Other customers — fill Nova's calendar for today and this week
  book({ biz: "b-nova", svc: 1, pro: 2, dayOffset: 0, pick: 1, customerId: "u-neta", status: "confirmed" });
  book({ biz: "b-nova", svc: 2, pro: 1, dayOffset: 0, pick: 2, customerId: "u-shira", status: "confirmed" });
  book({ biz: "b-nova", svc: 0, pro: 0, dayOffset: 1, pick: 0, guestName: "רותם (טלפון)", status: "confirmed" });
  book({ biz: "b-nova", svc: 3, pro: 0, dayOffset: 5, pick: 0, customerId: "u-michal", status: "pending_approval", source: "b-nova-post0", inspo: ["b-nova-post0"], note: "רוצה דבש כמו בסרטון" });
  book({ biz: "b-nova", svc: 1, pro: 2, dayOffset: 3, pick: 5, customerId: "u-yoav", status: "confirmed" });
  book({ biz: "b-nova", svc: 0, pro: 2, dayOffset: -2, pick: 2, customerId: "u-neta", status: "no_show" });
  book({ biz: "b-nova", svc: 1, pro: 0, dayOffset: -4, pick: 1, customerId: "u-shira", status: "completed" });
  book({ biz: "b-nova", svc: 3, pro: 1, dayOffset: 6, pick: 1, customerId: "u-yoav", status: "rejected" }).cancelReason = "אין מספיק זמן למורכבות הזו ביום הזה";
  book({ biz: "b-blade", svc: 1, pro: 0, dayOffset: 1, pick: 2, customerId: "u-yoav", status: "confirmed", source: "b-blade-post0" });
  book({ biz: "b-blade", svc: 1, pro: 0, dayOffset: -9, pick: 1, customerId: "u-ron", status: "completed" });
  book({ biz: "b-atelier", svc: 0, pro: 1, dayOffset: -8, pick: 3, customerId: "u-neta", status: "completed" });
  book({ biz: "b-kav", svc: 0, dayOffset: -5, pick: 2, customerId: "u-michal", status: "completed" });

  // Reviews exist only for completed appointments (marked as sample)
  const review = (aptId: string, rating: number, text: string, reply?: string) => {
    const a = db.appointments.find((x) => x.id === aptId)!;
    db.reviews.push({
      id: `rv-${db.reviews.length + 1}`,
      appointmentId: a.id,
      businessId: a.businessId,
      professionalId: a.professionalId,
      customerId: a.customerId!,
      rating,
      text,
      reply: reply ? { text: reply, at: iso(now.minus({ days: 1 })) } : undefined,
      hidden: false,
      createdAt: iso(DateTime.fromISO(a.end).plus({ days: 1 })),
      isSample: true,
    });
  };
  review(past2.id, 5, "גלים בדיוק כמו בסרטון. החזיק עד הערב!", "תודה דנה! מחכות לך שוב");
  const completed = db.appointments.filter((a) => a.status === "completed" && a.id !== past1.id && a.id !== past2.id);
  review(completed[0].id, 4, "מקצועית ונעימה, קצת המתנה בכניסה.");
  review(completed[1].id, 5, "הפייד הכי נקי שעשו לי.", "תודה רון!");
  review(completed[2].id, 5, "הג׳ל מחזיק כבר שלושה שבועות בלי שבר.");
  review(completed[3].id, 3, "איפור יפה אבל התחיל באיחור של 20 דקות.");

  // Messages
  db.conversations.push(
    {
      id: "cv1",
      customerId: "u-dana",
      businessId: "b-nova",
      appointmentId: a1.id,
      createdAt: iso(now.minus({ days: 2 })),
      lastReadAt: { "u-dana": iso(now.minus({ hours: 3 })) },
      messages: [
        { id: "m1", senderId: "u-dana", text: "היי! אפשר משהו בסגנון הזה? רוצה לשמור על האורך", attachmentPostId: "b-nova-post1", createdAt: iso(now.minus({ days: 2 })) },
        { id: "m2", senderId: "u-owner-nova", text: "בטח! זה יתאים לך מאוד. נתאים את השכבות לצורת הפנים. נתראה בתור 😊", createdAt: iso(now.minus({ hours: 2 })) },
      ],
    },
    {
      id: "cv2",
      customerId: "u-dana",
      businessId: "b-libi",
      appointmentId: a2.id,
      createdAt: iso(now.minus({ days: 1 })),
      lastReadAt: { "u-dana": iso(now), "u-owner-libi": iso(now.minus({ days: 1 })) },
      messages: [{ id: "m3", senderId: "u-dana", text: "שלחתי בקשה לאיפור כלה, אשמח לאישור 🙏", createdAt: iso(now.minus({ days: 1 })) }],
    },
    {
      id: "cv3",
      customerId: "u-yoav",
      businessId: "b-nova",
      createdAt: iso(now.minus({ hours: 6 })),
      lastReadAt: {},
      messages: [{ id: "m4", senderId: "u-yoav", text: "יש לכם תור לפן מחר בערב?", createdAt: iso(now.minus({ hours: 6 })) }],
    },
  );

  // Notifications
  const n = (userId: string, category: "appointments" | "messages" | "social" | "business", title: string, body: string, link: string, hoursAgo: number, read = false) =>
    db.notifications.push({ id: `n${db.notifications.length + 1}`, userId, category, title, body, link, createdAt: iso(now.minus({ hours: hoursAgo })), read });
  n("u-dana", "messages", "הודעה חדשה מסטודיו נובה", "בטח! זה יתאים לך מאוד…", "/messages/cv1", 2);
  n("u-dana", "appointments", "תזכורת: מחר בסטודיו נובה", "תספורת נשים", `/appointments/${a1.id}`, 5, true);
  n("u-dana", "social", "אטלייה לק פרסמו רילס חדש", "נוד חלבי לשגרה", "/post/b-atelier-post0", 7);
  n("u-owner-nova", "appointments", "בקשת תור חדשה", "מיכל אברהם מבקשת בלייאז׳", "/manage/appointments", 3);
  n("u-owner-nova", "messages", "הודעה חדשה", "יואב לוי: יש לכם תור לפן מחר בערב?", "/messages/cv3", 6);

  // Reports
  db.reports.push(
    { id: "rp1", reporterId: "u-neta", targetType: "comment", targetId: "c4", reason: "ספאם", details: "קישור פרסומי", status: "open", createdAt: iso(now.minus({ hours: 8 })) },
    { id: "rp2", reporterId: "u-ron", targetType: "post", targetId: "b-rishon-post0", reason: "שימוש בתמונה ללא רשות", details: "דיווח לדוגמה לבדיקת תור הדיווחים", status: "open", createdAt: iso(now.minus({ hours: 20 })) },
    { id: "rp3", reporterId: "u-michal", targetType: "review", targetId: "rv-5", reason: "תוכן פוגעני", details: "", status: "dismissed", resolution: "הביקורת עניינית — לא הוסרה", resolvedBy: "u-admin", createdAt: iso(now.minus({ days: 3 })) },
  );

  // Campaigns (simulated promotion — no real billing)
  db.campaigns.push(
    { id: "cmp1", businessId: "b-nova", postId: "b-nova-post0", cityIds: ["tlv", "rg"], budget: 500, start: iso(now.minus({ days: 3 })), end: iso(now.plus({ days: 11 })), status: "active", metrics: { impressions: 8420, clicks: 312, bookings: 9 }, createdAt: iso(now.minus({ days: 3 })) },
    { id: "cmp2", businessId: "b-gloss", postId: "b-gloss-post1", cityIds: ["hrz"], budget: 250, start: iso(now.minus({ days: 10 })), end: iso(now.plus({ days: 4 })), status: "paused", metrics: { impressions: 2100, clicks: 74, bookings: 2 }, createdAt: iso(now.minus({ days: 10 })) },
  );

  // Simulated payment records
  for (const a of db.appointments.filter((x) => x.payment.status === "paid_demo")) {
    db.payments.push({ id: `pay-${a.id}`, appointmentId: a.id, businessId: a.businessId, customerId: a.customerId ?? "", amount: a.payment.amount, status: "succeeded_demo", createdAt: a.createdAt });
  }
  db.payments.push({ id: "pay-failed-1", appointmentId: db.appointments[2].id, businessId: "b-atelier", customerId: "u-dana", amount: 50, status: "failed_demo", createdAt: iso(now.minus({ minutes: 3 })) });

  db.audit.push({ id: "au1", actorId: "u-admin", action: "approve_business", targetType: "business", targetId: "b-rishon", reason: "פרטי העסק נבדקו", createdAt: iso(now.minus({ days: 20 })) });

  // Analytics history (demo numbers)
  for (const p of db.posts) {
    for (let k = 0; k < Math.min(40, Math.round(p.views / 150)); k++) db.analytics.push({ id: `ev-${p.id}-${k}`, type: "view", businessId: p.businessId, postId: p.id, at: iso(now.minus({ hours: k * 5 })) });
    for (let k = 0; k < Math.round(p.views / 900); k++) db.analytics.push({ id: `bs-${p.id}-${k}`, type: "booking_start", businessId: p.businessId, postId: p.id, at: iso(now.minus({ hours: k * 13 })) });
  }
  for (const b of db.businesses) for (let k = 0; k < 18; k++) db.analytics.push({ id: `pv-${b.id}-${k}`, type: "profile_visit", businessId: b.id, at: iso(now.minus({ hours: k * 9 })) });

  // Stories (24h) — sample content, made from the same original illustrations
  const storyOf = (id: string, biz: string, file: string, hoursAgo: number, extra: Partial<Story> = {}) => {
    const created = now.minus({ hours: hoursAgo });
    const isVideo = !file.startsWith("square-") && !file.startsWith("cover-");
    db.stories.push({
      id,
      businessId: biz,
      media: isVideo ? { ...video(file), overlays: extra.media?.overlays } : { ...image(file), overlays: extra.media?.overlays },
      createdAt: iso(created),
      expiresAt: iso(created.plus({ hours: 24 })),
      viewers: [],
      likedBy: [],
      isSample: true,
      ...extra,
      ...(extra.media ? { media: { ...(isVideo ? video(file) : image(file)), ...extra.media } } : {}),
    });
  };
  const ov = (text: string, y = 70, style: "plain" | "box" | "outline" = "box") => [{ id: `ov-${text.length}-${y}`, text, x: 50, y, style, color: "#ffffff" }];
  storyOf("st-nova-1", "b-nova", "hair-honey", 2, { serviceId: "b-nova-s3", media: { ...video("hair-honey"), overlays: ov("נשארו 2 מקומות לבלייאז׳ השבוע") } });
  storyOf("st-nova-2", "b-nova", "square-hair", 1, { media: { ...image("square-hair"), overlays: ov("מאחורי הקלעים ✂️", 18, "outline") } });
  storyOf("st-blade-1", "b-blade", "fade-dark", 5, { serviceId: "b-blade-s1", media: { ...video("fade-dark"), overlays: ov("הכיסא פנוי היום מ־17:00") } });
  storyOf("st-atelier-1", "b-atelier", "nails-nude", 3, { sharedPostId: "b-atelier-post0" });
  storyOf("st-chrome-1", "b-chrome", "nails-chrome", 8, { media: { ...video("nails-chrome"), overlays: ov("כרום פנינה — הטרנד של הסתיו") } });
  storyOf("st-libi-1", "b-libi", "makeup-rose", 4, { serviceId: "b-libi-s0", media: { ...video("makeup-rose"), overlays: ov("פנוי למחר בערב 💄") } });
  storyOf("st-gloss-1", "b-gloss", "blowout-honey", 11);
  storyOf("st-brow-1", "b-brow", "lashes-soft", 6, { media: { ...video("lashes-soft"), overlays: ov("לפני ← אחרי") } });
  storyOf("st-old", "b-skin", "skincare-light", 30); // already expired — never shown
  const fans = ["u-dana", "u-neta", "u-shira", "u-michal", "u-yoav", "u-ron"];
  for (const st of db.stories) {
    st.viewers = fans.slice(0, 2 + (st.id.length % 4)).map((userId, k) => ({ userId, at: iso(now.minus({ minutes: 20 + k * 37 })) }));
    st.likedBy = fans.slice(0, st.id.length % 3);
  }
  // Watch-time history for creator insights (demo numbers)
  const sources: TrafficSource[] = ["feed", "feed", "feed", "following", "discover", "profile", "share", "nearby", "tag", "story"];
  let seedN = 11;
  const rnd = () => ((seedN = (seedN * 9301 + 49297) % 233280) / 233280);
  for (const p of db.posts.filter((x) => x.kind === "reel")) {
    const len = 7;
    const quality = 0.45 + (p.likedBy.length % 7) / 14; // some reels hold attention better
    for (let k = 0; k < Math.min(60, Math.round(p.views / 90)); k++) {
      const watched = Math.min(len * 2, Math.max(0.6, len * quality * (0.3 + rnd() * 1.6)));
      db.analytics.push({ id: `w-${p.id}-${k}`, type: "watch", businessId: p.businessId, postId: p.id, seconds: Math.round(watched * 10) / 10, completed: watched >= len * 0.95, source: sources[Math.floor(rnd() * sources.length)], at: iso(now.minus({ hours: k * 3 + rnd() * 3 })) });
    }
  }
  for (const b of db.businesses) for (let k = 0; k < 9; k++) db.analytics.push({ id: `fl-${b.id}-${k}`, type: "follow", businessId: b.id, at: iso(now.minus({ days: k * 3 + 1 })) });

  return db;
}
